base_url = "https://pky.me"
title = "MJ Pooladkhay"
description = "MJ Pooladkhay's personal website"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false                                # Keep this false, search is temporarily unsupported
generate_feeds = true
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css" },
    { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "MJ Pooladkhay"
id = "pky.me"
bio = "I'm a computer programmer with a deep interest in Compilers and Process VMs, currently working under the title of Senior DevOps Engineer." # Your bio
avatar = "img/avatar.webp" # Your avatar
links = [
    { name = "Email", icon = "email", url = "mailto:mj@pky.me" },
    # { name = "GitHub", icon = "github", url = "https://github.com/pooladkhay" },
]

homepage_layout = "list" # "about" | "list" | "recent"

recent_max = 15
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "github", path = "https://github.com/pooladkhay", is_external = true },
    # { name = "projects", path = "/projects", is_external = false },
    # { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = false      # Whether to display your id on homepage
blog_categorized = true # Whether to categorize blog posts
blur_effect = true      # Whether to turn on blur effect on navigation bar
back_to_top = true      # Whether to show back-to-top button on post pages

toc = true               # Whether to show Table-Of-Contents by default
copy = true              # Whether to add a copy button on code blocks by default
comment = false          # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true      # Whether to display tags on post pages by default
truncate_summary = false # Whether to truncate the summary of a post by default

outdate_alert = false                                          # Whether to show outdate alert by default
outdate_alert_days = 120                                       # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2024 pky.me"
footer_credits = true

not_found_title = "404"
not_found_error_text = "You know what it means!"
not_found_recover_text = "« back to home »"
